### ISSUE TITLE
Перейти с lstlistings на minted

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/Blanks-4LaTeX#1]
В пакете `lstlistings` нет поддержки кириллицы. Пора переходить на `minted`, чтобы иметь возможность писать в листингах комментарии по-русски.

**Comment by TonitaN** [comment]
Переход сделан, кириллица заработала и гарнитуры подогнаны под `TestVkr`, но теперь нумерация строк в листингах вылазит за поля, на что `TestVkr` ругается. Придётся дополнительно переопределять окружение `listing` как `minipage`.

**Comment by Mazdaywik** [comment]
Если бы в комментарий коммита был добавлен `#1`, то коммит отобразился бы здесь.
